version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
    groups:
      next:
        patterns: ['next', 'eslint-config-next', '@next/*']
      prisma:
        patterns: ['prisma', '@prisma/*']
      testing:
        patterns: ['vitest', '@vitest/*', '@playwright/*', '@testing-library/*']

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }

  - package-ecosystem: docker
    directory: /docker
    schedule: { interval: monthly }
